process.env.success = JSON.stringify({
    "user_created" : "User created successfully",
    "logout_successfully" : "Logout successfully",
    "profile_photo_uploaded" : "Photo uploaded successfully",
    "adventure_created" : "Adventure created successfully",
    "adventure_updated" : "Adventure updated successfully",
    "adventure_deleted" : "Adventure deleted successfully",
    "adventure_tag_created" : "Tags assigned successfully",
    "infoadventure_created" : "InfoAdventure created successfully",
    "infoadventure_updated" : "InfoAdventure updated successfully",
    "infoadventure_deleted" : "InfoAdventure deleted successfully",
    "stop_created" : "Stop created successfully",
    "stop_updated" : "Stop updated successfully",
    "stop_deleted" : "Stop deleted successfully",
    "stop_images_uploaded" : "StopImages uploaded result",
    "bankaccount_created" : "Bank Account created successfully",
    "bankaccount_updated" : "Bank Account updated successfully",
    "bankaccount_deleted" : "Bank Account deleted successfully",
    "profile_photo_uploaded" : "Photo uploaded successfully",
    "card_created" : "Card created successfully",
    "card_updated" : "Card updated successfully",
    "card_deleted" : "Card deleted successfully",
    "recommendation_created" : "Recommendation created successfully",
    "recommendation_updated" : "Recommendation updated successfully",
    "recommendation_deleted" : "Recommendation deleted successfully",
    "stopphone_created" : "Stopphone created successfully",
    "stopphone_updated" : "Stopphone updated successfully",
    "stopphone_deleted" : "Stopphone deleted successfully",
    "caution_created" : "Caution created successfully",
    "caution_updated" : "Caution updated successfully",
    "caution_deleted" : "Caution deleted successfully",
    "typeTransport_created" : "TypeTransport created successfully",
    "typeTransport_updated" : "TypeTransport updated successfully",
    "typeTransport_deleted" : "TypeTransport deleted successfully",
    "tag_created" : "Tag created successfully",
    "tag_updated" : "Tag updated successfully",
    "tag_deleted" : "Tag deleted successfully",
    "buy_adventure_created" : "Buy Adventure created successfully",
    "buy_adventure_updated" : "Buy Adventure updated successfully",
    "buy_adventure_deleted" : "Buy Adventure deleted successfully",
})
